#!/usr/bin/env python3
"""
Personal Finance Manager — Setup Wizard

Run this once after downloading the app to configure your database,
build the frontend, and set up the Python environment.

Usage:
    python3 install.py          (Mac/Linux)
    python install.py           (Windows)
"""

import os
import sys
import subprocess
import platform
import shutil
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
BACKEND_DIR = SCRIPT_DIR / "backend"
FRONTEND_DIR = SCRIPT_DIR / "frontend"
IS_WINDOWS = platform.system() == "Windows"
PYTHON = sys.executable
TOTAL_STEPS = 7

BANNER = """
  ╔══════════════════════════════════════════════════════════╗
  ║      Personal Finance Manager — Setup Wizard             ║
  ║      Track your bank transactions, investments,          ║
  ║      and property loans in one place.                    ║
  ╚══════════════════════════════════════════════════════════╝
"""


# ── Terminal helpers ──────────────────────────────────────────

def step(n, msg):
    print(f"\n  [{n}/{TOTAL_STEPS}] {msg}")


def ok(msg):
    print(f"        ✓  {msg}")


def warn(msg):
    print(f"        !  {msg}")


def err(msg):
    print(f"        ✗  {msg}")


def run(cmd, cwd=None, env=None, capture=False):
    """Run a subprocess command, raising on non-zero exit."""
    kwargs = {"cwd": cwd, "env": env}
    if capture:
        kwargs["capture_output"] = True
        kwargs["text"] = True
    return subprocess.run(cmd, check=True, **kwargs)


# ── Step 0: Database choice ───────────────────────────────────

def prompt_db_choice() -> int:
    print(BANNER)
    print("  Which database would you like to use?\n")
    print("    1)  SQLite          (recommended — no extra software needed)")
    print("    2)  Docker+MariaDB  (requires Docker Desktop)")
    print("    3)  External MariaDB (you already have MariaDB running)")
    print()
    while True:
        choice = input("  Enter 1, 2, or 3  [default: 1]: ").strip() or "1"
        if choice in ("1", "2", "3"):
            return int(choice)
        print("  Please enter 1, 2, or 3.")


# ── Step 1: Prerequisites ─────────────────────────────────────

def check_prerequisites(db_choice: int):
    step(1, "Checking prerequisites...")
    passed = True

    # Python version
    v = sys.version_info
    if v < (3, 11):
        err(f"Python 3.11+ required — you have {v.major}.{v.minor}. Download from https://python.org")
        passed = False
    else:
        ok(f"Python {v.major}.{v.minor}.{v.micro}")

    # Node.js
    node = shutil.which("node") or shutil.which("node.exe")
    if not node:
        err("Node.js not found — install v18+ from https://nodejs.org")
        passed = False
    else:
        try:
            r = subprocess.run([node, "--version"], capture_output=True, text=True)
            ok(f"Node.js {r.stdout.strip()}")
        except Exception:
            err("Node.js found but could not check version")
            passed = False

    # npm
    npm = shutil.which("npm") or shutil.which("npm.cmd")
    if not npm:
        err("npm not found — install Node.js from https://nodejs.org")
        passed = False
    else:
        ok("npm found")

    # Docker (only needed for MariaDB option)
    if db_choice == 2:
        docker = shutil.which("docker")
        if not docker:
            err("Docker not found — install Docker Desktop from https://docker.com")
            passed = False
        else:
            r = subprocess.run(["docker", "info"], capture_output=True)
            if r.returncode != 0:
                err("Docker is not running — please start Docker Desktop and try again")
                passed = False
            else:
                ok("Docker running")

    if not passed:
        print("\n  Please fix the issues above and run install.py again.\n")
        sys.exit(1)

    ok("All prerequisites met")


# ── Step 2: Database configuration ───────────────────────────

def configure_env(db_choice: int):
    step(2, "Configuring database...")
    env_path = BACKEND_DIR / ".env"

    lines = ["# Generated by install.py — edit to change settings", ""]

    if db_choice == 1:
        lines += [
            "DB_TYPE=sqlite",
            "SQLITE_PATH=data/finance.db",
        ]
        ok("SQLite selected — database file will be created at backend/data/finance.db")

    elif db_choice == 2:
        lines += [
            "DB_TYPE=mariadb",
            "DB_HOST=localhost",
            "DB_PORT=3306",
            "DB_USER=finance_user",
            "DB_PASSWORD=finance_pass",
            "DB_NAME=finance_app",
        ]
        ok("Docker+MariaDB selected")

    else:
        print("\n  Enter your MariaDB connection details:")
        host = input("    Host     [localhost]: ").strip() or "localhost"
        port = input("    Port     [3306]:     ").strip() or "3306"
        user = input("    User:                ").strip()
        password = input("    Password:            ").strip()
        db_name = input("    Database [finance_app]: ").strip() or "finance_app"
        lines += [
            "DB_TYPE=mariadb",
            f"DB_HOST={host}",
            f"DB_PORT={port}",
            f"DB_USER={user}",
            f"DB_PASSWORD={password}",
            f"DB_NAME={db_name}",
        ]
        ok(f"External MariaDB at {host}:{port}/{db_name}")

    lines += [
        "",
        "DEBUG=False",
        "FRONTEND_URL=http://localhost:8000",
    ]

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ok(f"Configuration saved to {env_path.relative_to(SCRIPT_DIR)}")


# ── Step 3: Start Docker DB (MariaDB option only) ─────────────

def start_docker_db():
    step(3, "Starting MariaDB (Docker)...")

    r = subprocess.run(["docker", "compose", "version"], capture_output=True)
    compose = ["docker", "compose"] if r.returncode == 0 else ["docker-compose"]

    run(compose + ["up", "-d", "finance-db"], cwd=SCRIPT_DIR)

    print("        Waiting for MariaDB", end="", flush=True)
    for _ in range(30):
        r = subprocess.run(
            ["docker", "exec", "finance-db",
             "healthcheck.sh", "--connect", "--innodb_initialized"],
            capture_output=True,
        )
        if r.returncode == 0:
            print(" ready!")
            break
        print(".", end="", flush=True)
        time.sleep(1)
    else:
        print()
        warn("MariaDB didn't become healthy in 30s — continuing anyway")


def skip_docker():
    step(3, "Skipping Docker (not required for this database option)...")
    ok("Skipped")


# ── Step 4: Python virtual environment ───────────────────────

def setup_python_venv():
    step(4, "Setting up Python environment...")
    venv_dir = BACKEND_DIR / "venv"

    if not venv_dir.exists():
        print("        Creating virtual environment...")
        run([PYTHON, "-m", "venv", str(venv_dir)])
        ok("Virtual environment created")
    else:
        ok("Virtual environment already exists")

    pip = (
        venv_dir / "Scripts" / "pip.exe"
        if IS_WINDOWS
        else venv_dir / "bin" / "pip"
    )
    print("        Installing Python packages (this may take a minute)...")
    run([str(pip), "install", "-r", str(BACKEND_DIR / "requirements.txt"), "-q"])
    ok("Python packages installed")


# ── Step 5: Frontend build ────────────────────────────────────

def build_frontend():
    step(5, "Building frontend...")
    npm_cmd = "npm.cmd" if IS_WINDOWS else "npm"

    print("        Installing npm packages...")
    run([npm_cmd, "install", "--silent"], cwd=FRONTEND_DIR)

    print("        Building React app...")
    env = {**os.environ, "VITE_API_BASE_URL": ""}
    run([npm_cmd, "run", "build"], cwd=FRONTEND_DIR, env=env)
    ok("Frontend built")


# ── Step 6: Verification ──────────────────────────────────────

def verify():
    step(6, "Verifying installation...")
    dist = FRONTEND_DIR / "dist"
    index = dist / "index.html"
    if index.is_file():
        ok("Frontend build verified")
    else:
        warn("Frontend dist/index.html not found — try running: npm run build")

    venv_python = (
        BACKEND_DIR / "venv" / "Scripts" / "python.exe"
        if IS_WINDOWS
        else BACKEND_DIR / "venv" / "bin" / "python"
    )
    if venv_python.exists():
        ok("Python virtual environment verified")
    else:
        warn("Virtual environment not found — try running: python3 install.py")


# ── Step 7: Success ───────────────────────────────────────────

def print_success():
    step(7, "Setup complete!")
    print()
    print("  ╔══════════════════════════════════════════════════════════╗")
    print("  ║  All done! To start the app:                            ║")
    print("  ║                                                          ║")
    if IS_WINDOWS:
        print("  ║    python start.py                                      ║")
    else:
        print("  ║    python3 start.py                                     ║")
    print("  ║                                                          ║")
    print("  ║  Then open: http://localhost:8000                        ║")
    print("  ╚══════════════════════════════════════════════════════════╝")
    print()


# ── Main ──────────────────────────────────────────────────────

def main():
    db_choice = prompt_db_choice()

    check_prerequisites(db_choice)
    configure_env(db_choice)

    if db_choice == 2:
        start_docker_db()
    else:
        skip_docker()

    setup_python_venv()
    build_frontend()
    verify()
    print_success()


if __name__ == "__main__":
    main()
